"""Every sim script must import STANDALONE, with no PYTHONPATH help.

WHY THIS EXISTS
---------------
Moving rom_envelope into nova_ops (issue #143) broke EVERY script in this
directory: they put only `ros2_ws/src/nova_locomotion` on sys.path, and
leg_ik had started importing `nova_ops.rom_envelope`, so the first real run
died with

    ModuleNotFoundError: No module named 'nova_ops'

The ROS unit suite passed 158/158 through all of it, because it runs with both
packages already on PYTHONPATH. Nothing exercised these files the way a person
actually runs them — `../../.venv/bin/python probe_lift_force.py` — so the
breakage was invisible until an artifact was regenerated by hand.

That is exactly the gap this closes. The subprocess below runs with PYTHONPATH
STRIPPED, so each module has to establish its own sys.path exactly as it does
for a real invocation. Importing is enough: every executable here is
`__main__`-guarded, so module-level import work runs but no main() does.

ONE SUBPROCESS PER SCRIPT, deliberately. The first version imported them all in
a single process to amortise jax/brax, and a negative control proved that cannot
work: an alphabetically-earlier script (probe_lift_force) inserts the nova_ops
path into sys.path, and it persists for the rest of the loop — so re-introducing
the exact original break still PASSED. Shared interpreter state masks precisely
the failure this exists to catch. Isolation is the whole point, not an
optimisation to trade away.
"""
import os
import subprocess
import sys
import textwrap
from pathlib import Path

HERE = Path(__file__).parent

_CHILD = textwrap.dedent(
    """
    import importlib.util, sys
    name = sys.argv[1]
    spec = importlib.util.spec_from_file_location("_probe", name)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    """
)


def _scripts():
    return sorted(
        p.name
        for p in HERE.glob("*.py")
        if not p.name.startswith("test_") and p.name != "conftest.py"
    )


def test_every_sim_script_imports_without_pythonpath():
    scripts = _scripts()
    assert scripts, "no sim scripts found — did this file move?"

    env = {k: v for k, v in os.environ.items() if k != "PYTHONPATH"}
    env["JAX_PLATFORMS"] = "cpu"          # don't probe for a GPU in a unit test
    # A GL backend must be VALID FOR THIS PLATFORM: mujoco validates MUJOCO_GL at
    # import. rollout.py does os.environ.setdefault("MUJOCO_GL", "egl") — correct
    # for its Colab home, and its comment says an explicit value wins, so supply
    # one rather than "fixing" a script that is not broken. No GL context is
    # created at import; this only has to parse.
    env.setdefault("MUJOCO_GL", "cgl" if sys.platform == "darwin" else "egl")

    failures = {}
    for name in scripts:
        proc = subprocess.run(
            [sys.executable, "-c", _CHILD, name],
            cwd=HERE,
            env=env,
            capture_output=True,
            text=True,
            timeout=300,
        )
        if proc.returncode != 0:
            tail = (proc.stderr.strip().splitlines() or ["(no stderr)"])[-1]
            failures[name] = tail[:200]
    assert not failures, "sim scripts that do not import standalone:\n" + "\n".join(
        f"  {name}: {err}" for name, err in sorted(failures.items())
    )
