"""POSTURE-AWARE chassis hfe bounds (2026-07-25).

⚠⚠ THE REAR ROWS OF THE TABLE ARE NOT VALID FOR THE BUILT ROBOT (found
2026-07-26, CAD review). They were swept with the rear hip placed as a pure
TRANSLATION of the front, but the same shoulder part is used at both trunk ends
and its flange bolts to the trunk end face, so the rear hip is the front
placement YAWED 180 deg about Z. Derivation + measurements:
hardware/cad/chassis/check_fit.py coax_to_trunk_bases() (fixed there
2026-07-26) and docs/cad-review-2026-07-26.md.

What that means here, concretely:
  * The correct rear window equals the FRONT window in the leg's own frame
    (they are mirror images): [-94, +66] at haa 0 / kfe -109 and [-94, +14] at
    haa -15 / kfe -109 — vs the flat [-77.2, +95] (haa 0) / [-37.2, +95]
    (haa -15) the stored rear rows carry at EVERY kfe. The stored rear rows have
    no kfe dependence at all, which is itself the tell: with the rear leg placed
    backwards its knee folds away from the chassis, so kfe stopped mattering.
  * The stored rear window is LOOSE on the constrained side — by ~11 deg at
    haa 0 and considerably more at inboard haa — and this gate is now the SOLE
    chassis protection (limits.py loosened the hfe scalar to mechanical +-86 in
    the same 2026-07-25 batch). Treat rear-leg hfe as UNVERIFIED until the table
    is regenerated by hfe_envelope.py on a machine with the real servo.stl.
  * Regenerating also has to pin the leg-local -> canonical hfe SIGN for the
    yawed rear hips (their local +hfe is the opposite world rotation from the
    front's). This module documents a canonical convention for haa only; hfe has
    none. Same class of defect as #153/#155 (per-joint sign), so treat the sign
    as a deliverable of the regeneration, not an afterthought.
  * Conservative interim, if the robot must move before then: intersect the rear
    rows with the FRONT rows AND their mirror (i.e. a symmetric window) — safe
    under either sign reading, at the cost of clipping deep-fold rear postures.
    Not applied here: it changes runtime behaviour and clips gait, so it is the
    owner's call.


The chassis ROM was carried as a single scalar — "hfe toward-trunk fold +50 deg"
— but the constraint is 3-dimensional: how far the leg can fold before the tibia
flank reaches the riser skirt (or the belly pack / rails / head) depends on how
far the hip is splayed and how far the knee is folded at the same time.

MEASURED (hardware/cad/chassis/hfe_envelope.py, against riser_bay / battery_pocket
/ pack / skid rails / head, with check_fit's rear hip placement corrected from a
reflection to a real rotation):

    FRONT hfe_max    haa +40 (full outboard splay), kfe -109  ->  +51.7 deg
                     haa   0                      , kfe -109  ->  +70.6 deg
                     haa   0                      , kfe  -25  ->  +76.9 deg
    REAR  hfe_min    haa   0                                  ->  -80.1 deg

So +50 is very nearly the true worst case over the LEGAL haa range (+51.7) — the
scalar was right, it was just applied at every posture. Both primary gaits run
the front legs at haa 0 with kfe ~-98.8, where the real bound is +70.6; the trot's
+59.4 deg excursion has ~11 deg of margin there and only failed because it was
being checked against another posture's worst case.

CONVENTIONS
  * haa/hfe/kfe are CANONICAL (leg_ik frame): +haa = OUTBOARD for every leg.
  * Bounds are returned in RADIANS.
  * Lookup is CONSERVATIVE: a query between grid cells takes the TIGHTEST bound
    of the enclosing cells (max of the lows, min of the highs), and a query
    outside the grid is clamped to the edge cell. Never interpolate toward a
    looser bound — the sampled surface is not guaranteed monotonic between cells.
  * Unknown leg -> the intersection of the FRONT and REAR envelopes.
  * The table is a CLEARANCE boundary, not first contact: it was swept with a
    proximity test at rom_envelope_table.CLEARANCE_MM, so the required gap is
    already inside the stored numbers. MARGIN_DEG is an extra hook, now 0.

⚠ This is the KINEMATIC truth. The scalars derived from it downstream —
LegParams.hfe_max, nova.urdf.xacro hfe_fold, sim/nova_mjx/build_mjcf.HFE_FOLD and
nova_ops.safety_envelope.limits — are still set to the worst case, so the runtime
will still clamp to +50 until they are regenerated from this table. Raising them
is a hardware-affecting change and is deliberately NOT done here.
"""

from __future__ import annotations

import math
from typing import Optional, Tuple

from nova_ops.rom_envelope_table import ENVELOPE, HAAS, KFES

# The required gap now lives in the MEASUREMENT, not here (issue #146 / S4).
# hfe_envelope.py sweeps the boundary with a proximity test — "the leg comes
# within CLEARANCE_MM of the chassis" — instead of a containment flip, so the
# stored bounds already stand off the geometry by a real physical distance.
#
# That fixes two things an angular back-off could not. Containment only trips
# once a SAMPLED point is inside the solid, which is late twice over: the cloud
# is sparse (a tangential graze can register zero points while surfaces touch)
# and a 2.5 deg scan step is ~6.5 mm of arc at the tibia flank, enough to step
# over a boss entirely. Proximity sees a feature from CLEARANCE_MM away. And a
# degree is not a distance: the retired 5 deg was worth ~5 mm at haa +40 but
# noticeably more at haa 0, so it silently varied by posture.
#
# Kept at 0 as a deliberate hook — set it only to add margin ON TOP of the
# measured gap, never as a substitute for regenerating the table.
MARGIN_DEG = 0.0

FRONT_ENDS = frozenset({"FL", "FR"})
REAR_ENDS = frozenset({"RL", "RR"})


def _bracket(vals, x):
    """Indices of the grid cells enclosing x (clamped at the edges)."""
    if x <= vals[0]:
        return (0, 0)
    if x >= vals[-1]:
        return (len(vals) - 1, len(vals) - 1)
    for i, v in enumerate(vals):
        if v == x:
            return (i, i)  # exact grid hit — no need to widen the bracket
    hi = next(i for i, v in enumerate(vals) if v >= x)
    return (hi - 1, hi)


def _end_bounds(end: str, haa_deg: float, kfe_deg: float) -> Tuple[float, float]:
    ia, ib = _bracket(HAAS, haa_deg)
    ka, kb = _bracket(KFES, kfe_deg)
    lo, hi = -1e9, 1e9
    for k in (KFES[ka], KFES[kb]):
        row = ENVELOPE[end][k]
        for i in (ia, ib):
            cell_lo, cell_hi = row[i]
            lo = max(lo, cell_lo)  # tightest low
            hi = min(hi, cell_hi)  # tightest high
    return lo, hi


def hfe_bounds(leg: Optional[str], haa: float, kfe: float) -> Tuple[float, float]:
    """Chassis-safe hfe interval (radians) for this leg at this (haa, kfe) posture.

    haa/kfe in radians, canonical frame. `leg` may be FL/FR/RL/RR; anything else
    (including None) yields the conservative intersection of both ends.
    """
    haa_deg, kfe_deg = math.degrees(haa), math.degrees(kfe)
    # PER-LEG since the 2026-07-25 review (S3): all four legs are swept, so a
    # known leg gets its own measured envelope rather than an assumed mirror.
    # (Measured L/R asymmetry is 0.0 deg, so the old assumption held — but it is
    # now verified rather than assumed.) Unknown leg -> intersect all four.
    ends = (leg,) if leg in ENVELOPE else tuple(ENVELOPE)
    lo, hi = -1e9, 1e9
    for end in ends:
        e_lo, e_hi = _end_bounds(end, haa_deg, kfe_deg)
        lo, hi = max(lo, e_lo), min(hi, e_hi)
    # BACK OFF from the measured FIRST-CONTACT boundary. The table is raw
    # geometry — the angle at which the leg TOUCHES. A gate that permits poses
    # right up to first contact permits grazing, and the point of the gate is
    # that a posture is refused because it would come NEAR the body.
    # 5 deg matches the convention the project already used: the chassis gate
    # measured front skirt contact at ~+55 and the published cap was +50.
    # Policy lives here, not in the table, so the margin is tunable and the
    # measurement stays a measurement.
    lo, hi = lo + MARGIN_DEG, hi - MARGIN_DEG
    if lo > hi:  # margin swallowed the cell — refuse it all
        mid = 0.5 * (lo + hi)
        lo = hi = mid
    return math.radians(lo), math.radians(hi)
